export const REQUEST_GET_ALL_CONVERSATIONS = "REQUEST_GET_ALL_CONVERSATIONS"
export const SUCCESS_GET_ALL_CONVERSATIONS = "SUCCESS_GET_ALL_CONVERSATIONS"
export const FAIL_GET_ALL_CONVERSATIONS = "FAIL_GET_ALL_CONVERSATIONS"


export const REQUEST_GET_CHAT_MESSAGES = "REQUEST_GET_CHAT_MESSAGES"
export const SUCCESS_GET_CHAT_MESSAGES = "SUCCESS_GET_CHAT_MESSAGES"
export const FAIL_GET_CHAT_MESSAGES = "FAIL_GET_CHAT_MESSAGES"


export const REQUEST_CREATE_CHAT_MESSAGES = "REQUEST_CREATE_CHAT_MESSAGES"
export const SUCCESS_CREATE_CHAT_MESSAGES = "SUCCESS_CREATE_CHAT_MESSAGES"
export const FAIL_CREATE_CHAT_MESSAGES = "FAIL_CREATE_CHAT_MESSAGES"


export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL"
export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS"