export const REQUEST_FRIEND_CONNECTION = "REQUEST_FRIEND_CONNECTION"
export const SUCCESS_FRIEND_CONNECTION = "SUCCESS_FRIEND_CONNECTION"
export const FAIL_FRIEND_CONNECTION = "FAIL_FRIEND_CONNECTION"