export const REQUEST_SEND_FRIEND_REQUEST = "REQUEST_SEND_FRIEND_REQUEST"
export const SUCCESS_SEND_FRIEND_REQUEST = "SUCCESS_SEND_FRIEND_REQUEST"
export const FAIL_SEND_FRIEND_REQUEST = "FAIL_SEND_FRIEND_REQUEST"


export const REQUEST_GET_CONNECTION_REQUEST = "REQUEST_GET_CONNECTION_REQUEST"
export const SUCCESS_GET_CONNECTION_REQUEST = "SUCCESS_GET_CONNECTION_REQUEST"
export const FAIL_GET_CONNECTION_REQUEST = "FAIL_GET_CONNECTION_REQUEST"



