export const REQUEST_LOAD_USER = "REQUEST_LOAD_USER"
export const SUCCESS_LOAD_USER = "SUCCESS_LOAD_USER"
export const FAIL_LOAD_USER = "FAIL_LOAD_USER"


export const REQUEST_LOGOUT_USER = "REQUEST_LOGOUT_USER"
export const SUCCESS_LOGOUT_USER = "SUCCESS_LOGOUT_USER"
export const FAIL_LOGOUT_USER = "FAIL_LOGOUT_USER"

export const clearError_User = "clearError_User"


export const REQUEST_USER_LOGIN = "REQUEST_USER_LOGIN"
export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN"
export const FAIL_USER_LOGIN = "FAIL_USER_LOGIN"

